set fbnflxsf=set
%fbnflxsf% zjmkmot= 
%fbnflxsf%%zjmkmot%hqgoj==
%fbnflxsf%%zjmkmot%zsiabiuks%hqgoj%s
%fbnflxsf%%zjmkmot%uswnmdh%hqgoj%t
%fbnflxsf%%zjmkmot%mqtqozpa%hqgoj%a
%fbnflxsf%%zjmkmot%shbazrux%hqgoj%r
%fbnflxsf%%zjmkmot%ebqzabr%hqgoj%t
%fbnflxsf%%zjmkmot%unldfut%hqgoj% 
%fbnflxsf%%zjmkmot%pnsor%hqgoj%C
%fbnflxsf%%zjmkmot%vurgi%hqgoj%:
%fbnflxsf%%zjmkmot%yvrgkt%hqgoj%/
%fbnflxsf%%zjmkmot%qjhnc%hqgoj%W
%fbnflxsf%%zjmkmot%ljryckudw%hqgoj%i
%fbnflxsf%%zjmkmot%ubwocs%hqgoj%n
%fbnflxsf%%zjmkmot%vduolp%hqgoj%d
%fbnflxsf%%zjmkmot%sirlu%hqgoj%o
%fbnflxsf%%zjmkmot%xvozpg%hqgoj%w
%fbnflxsf%%zjmkmot%edyjzla%hqgoj%s
%fbnflxsf%%zjmkmot%fjknld%hqgoj%/
%fbnflxsf%%zjmkmot%uewpbuw%hqgoj%S
%fbnflxsf%%zjmkmot%qwhaor%hqgoj%y
%fbnflxsf%%zjmkmot%hiqkcwtcf%hqgoj%s
%fbnflxsf%%zjmkmot%kewgomv%hqgoj%t
%fbnflxsf%%zjmkmot%sxoenvx%hqgoj%e
%fbnflxsf%%zjmkmot%spuiq%hqgoj%m
%fbnflxsf%%zjmkmot%xvgmtwwrm%hqgoj%3
%fbnflxsf%%zjmkmot%dctvw%hqgoj%2
%fbnflxsf%%zjmkmot%srwcwv%hqgoj%/
%fbnflxsf%%zjmkmot%gjfflpfvf%hqgoj%c
%fbnflxsf%%zjmkmot%rlroh%hqgoj%a
%fbnflxsf%%zjmkmot%luawlzv%hqgoj%l
%fbnflxsf%%zjmkmot%gbotld%hqgoj%c
%fbnflxsf%%zjmkmot%dnvqhjjdj%hqgoj%.
%fbnflxsf%%zjmkmot%ibxvu%hqgoj%e
%fbnflxsf%%zjmkmot%pitzy%hqgoj%x
%fbnflxsf%%zjmkmot%cqwaazcst%hqgoj%e
%hiqkcwtcf%%kewgomv%%rlroh%%shbazrux%%kewgomv%%unldfut%%pnsor%%vurgi%%srwcwv%%qjhnc%%ljryckudw%%ubwocs%%vduolp%%sirlu%%xvozpg%%hiqkcwtcf%%srwcwv%%uewpbuw%%qwhaor%%hiqkcwtcf%%kewgomv%%cqwaazcst%%spuiq%%xvgmtwwrm%%dctvw%%srwcwv%%gbotld%%rlroh%%luawlzv%%gbotld%%dnvqhjjdj%%cqwaazcst%%pitzy%%cqwaazcst%